blueprint:
  name: ZHA - Aqara Single Rocker Switch (EU, No Neutral)
  description: Automate your Xiaomi Aqara Single Rocker using
    ZHA events.
  domain: automation
  input:
    aqara_rocker_switch:
      name: Select the Aqara Rocker Switch (Single Rocker)
      description: Aqara Rocker Switch (Single Rocker)
      selector:
        device:
          integration: zha
          manufacturer: LUMI
          entity:
          - domain:
            - sensor
            device_class:
            - switch
          multiple: false
    button_single_press:
      name: Single Press
      description: Action to run on single press
      default: []
      selector:
        action: {}
    button_double_press:
      name: Double Press
      description: Action to run on double press
      default: []
      selector:
        action: {}
    button_long_press:
      name: Long Press
      description: Action to run when button is long pressed (held down)
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input aqara_rocker_switch
action:
- variables:
    command: '{{ trigger.event.data.args.press_type }}'
- choose:
  - conditions:
    - '{{ command == ''single'' }}'
    sequence: !input button_single_press
  - conditions:
    - '{{ command == ''double'' }}'
    sequence: !input button_double_press
  - conditions:
    - '{{ command == ''hold'' }}'
    sequence: !input button_long_press
